### Create a sample

POST http://localhost:3000/v1/samples HTTP/1.1
content-type: application/json

{
    "name": "sample name"
}

### Get a sample
GET http://localhost:3000/v1/samples HTTP/1.1

### Update a sample
PATCH http://localhost:3000/v1/samples/:id HTTP/1.1

{
    "name": "update sample name"
}

### Delete a sample
DELETE http://localhost:3000/v1/samples/:id HTTP/1.1