version: "3.9"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
  db:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: sample
    ports:
      - 3306:3306
    volumes:
      - "./database/my.cnf:/etc/mysql/conf.d/my.cnf"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
volumes:
  db:
    driver: local